[LoRaWAN] Improve PHY behaviour, update beginABP, bugfixes
jgromes/RadioLib pull request #1080
Opened 2024-04-29 19:56 UTC by StevenCellist

Until TTS v3.30.0 (current version), the ABP keys are displayed incorrectly. With the upcoming TTS v3.30.1, the ABP keys are now displayed exactly as per spec. The `beginABP()` function from this PR onwards uses the exact same order of key arguments with exactly the same names. This also makes it non-obvious how to use LW v1.0.x session which are still not properly supported, as the F/SNwkSIntKeys are now required instead of NULL-default. (They can still be set to NULL.)

* [LoRaWAN] Change beginABP arguments to match official key names & TTN console
* [CI] Update flag for changed LoRaWAN key name

If running LoRaWAN mixed with another protocol sharing the same radio, the physical layer was not reconfigured completely for each uplink. Also, as reminded in Discussions recently, there was a possibility to overrule the Tx power without the LW stack knowing about this. To prevent this, the LW stack now completely configures the PHY layer for each up/downlink.
To accomodate this change and prevent useless configuration of Tx power upon receiving ADR requests or user configuration, the checks for the module's Tx power range in the respective module drivers is separated from their `setOutputPower()` functions into `checkOutputPower()`.

* [LoRaWAN] Configure the physical layer on each up/downlink
* Implement & split off checkOutputPower

Moreover, the persistent buffers address calculations in for the Nonces & Session buffers was prone to user error - in fact, the session buffer even contained 48 useless bytes because I made an error! The improved implementation isn't particularly easier to read, but sure is safer. (And as a bonus, reduces from 396 bytes to 348.)

* [LoRaWAN] Improve persistent buffers addresses

... and the other bugfixes / changes:

* [LoRaWAN] Add getter for Time-on-Air of last uplink
* Update keywords.txt
* [LoRaWAN] Only allow sending each MAC request once per uplink (and only if piggybacking space is available)
* [LoRaWAN] Prevent possible underflows / bad delays while handling downlink windows
* [LoRaWAN] Remove unnecessary dynamic array

2024-04-29 19:56 UTC, StevenCellist commented
This PR has been tested on EU868/OTAA using the Reference and Persistent sketches. Both feedback and additional tests are welcome.

2024-04-30 16:08 UTC, jgromes requested changes
Thank you @StevenCellist for another great contribution! I left some comments, but I think most of it can be addressed quite quickly.

2024-04-30 16:08 UTC, jgromes commented on src/modules/SX127x/SX1278.cpp
> +      *clipped = RADIOLIB_MAX(2, RADIOLIB_MIN(17, power));
Cppcheck (rightfully) complains about this one: https://github.com/jgromes/RadioLib/actions/runs/8884715530/job/24394437946?pr=1080#step:4:2427

2024-04-30 16:46 UTC, StevenCellist commented on src/modules/CC1101/CC1101.h
> +    int16_t checkOutputPower(int8_t power, int8_t* clipped, uint8_t* raw);
Actually, I don't know exactly how this inheritance stuff works. I thought I saw something similar for some of the other methods so thought I'd copy it over, but apparently that's not how it works ;)
How should I solve this? (Or can you do that?)

2024-04-30 16:47 UTC, StevenCellist commented on src/protocols/LoRaWAN/LoRaWAN.cpp
> +  (void)findDataRate(this->dataRates[RADIOLIB_LORAWAN_CHANNEL_DIR_UPLINK], &dr);
This method is problematic for modules that do not support SF7-SF12, as in some weird way maybe a datarate is going to be configured that is not supported by the module. The function does not account for this (yet). But low priority so leaving it as a TODO for now.

2024-04-30 16:47 UTC, StevenCellist commented on src/protocols/LoRaWAN/LoRaWAN.cpp
> +        state = this->phyLayer->checkOutputPower(power, &powerActual);
Same point as CC1101 with the `powerRaw` argument

2024-05-01 10:08 UTC, jgromes commented on src/modules/CC1101/CC1101.h
> +    int16_t checkOutputPower(int8_t power, int8_t* clipped, uint8_t* raw);
It works by haveing an exact match in the method signature (and preferrably, marking the overriding method as `override`). This also leads to the fact that you cannot have and overriding method which has some extra arguments, even if you do provide default values for them. An example is in `SX126x`:

```
/*!
      \brief Sets the module to standby mode (overload for PhysicalLayer compatibility, uses 13 MHz RC oscillator).
      \returns \ref status_codes
    */
    int16_t standby() override;

    /*!
      \brief Sets the module to standby mode.
      \param mode Oscillator to be used in standby mode. Can be set to RADIOLIB_SX126X_STANDBY_RC (13 MHz RC oscillator)
      or RADIOLIB_SX126X_STANDBY_XOSC (32 MHz external crystal oscillator).
      \param wakeup Whether to force the module to wake up. Setting to true will immediately attempt to wake up the module.
      \returns \ref status_codes
    */
    int16_t standby(uint8_t mode, bool wakeup = true);
```

Having just a single `standby(uint8_t mode = RADIOLIB_SX126X_STANDBY_XOSC, bool wakeup = true)` would not be able to override `PhysicalLayer::standby(void)`, that's why an additional `SX126x::standby(void)` is needed.

I will fix it in this branch, my guess is that you tested with SX126x which does not have this problem with `checkOutputPower`.

2024-05-01 10:55 UTC, HeadBoffin approved these changes
Random approval because Steven said so

2024-05-01 11:30 UTC, StevenCellist commented
@jgromes thank you, LGTM. As per @HeadBoffin: tested on US915/OTAA as well.

2024-05-01 11:35 UTC, jgromes approved these changes

2024-05-01 11:35 UTC, jgromes commented
@StevenCellist I pushed the changes and also tested using an SX1272 to make sure the overrides are OK so this should be good to go. Thanks!

2024-05-01 11:35 UTC, merged